# # Generated by Django 3.0.6 on 2020-06-20 08:52

# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
# import django.utils.timezone


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='NewsItem',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('target_url', models.CharField(max_length=250, unique=True)),
#                 ('date', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('title', models.CharField(max_length=250)),
#                 ('source', models.CharField(max_length=250)),
#                 ('fetch_date', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('image', models.CharField(blank=True, default=None, max_length=250, null=True)),
#                 ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
#                 ('body', models.CharField(blank=True, default=None, max_length=512, null=True)),
#                 ('cached_page', models.CharField(blank=True, default=None, max_length=120, null=True)),
#                 ('thumbnail', models.CharField(blank=True, default=None, max_length=120, null=True)),
#                 ('summary', models.CharField(blank=True, default=None, max_length=4096, null=True)),
#                 ('sentiment', models.CharField(blank=True, default=None, max_length=20, null=True)),
#                 ('publication_state', models.CharField(blank=True, choices=[('P', 'Published'), ('A', 'Approved'), ('D', 'Discarded'), ('', '-')], default='', max_length=1, verbose_name='PubStatus')),
#                 ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Rating',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('rating', models.IntegerField(choices=[(-1, 'Bad'), (0, 'Neutral'), (1, 'Good'), (2, 'Awesome')], default=0)),
#                 ('date', models.DateTimeField(auto_now=True)),
#                 ('newsItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restapi.NewsItem')),
#                 ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#     ]
