# Generated by Django 2.2.7 on 2019-11-12 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restapi', '0002_auto_20191112_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItemRating',
            new_name='Rating',
        ),
    ]
