# Generated by Django 2.2.7 on 2019-11-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0003_auto_20191112_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="ratings",
            field=models.ManyToManyField(to="restapi.Rating"),
        ),
    ]
