# Generated by Django 2.2.7 on 2019-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_newsitem_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='ratings',
            field=models.ManyToManyField(default=None, null=True, related_name='ratings', to='restapi.Rating'),
        ),
    ]
