# Generated by Django 2.2.7 on 2019-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20191112_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='ratings',
        ),
    ]
