# Generated by Django 2.2.7 on 2019-11-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0008_remove_newsitem_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="newsItem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="restapi.NewsItem",
            ),
        ),
    ]
