# Generated by Django 3.0.2 on 2020-04-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20200410_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='username',
        ),
    ]
