# Generated by Django 3.0.2 on 2020-04-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_auto_20200411_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='user',
        ),
    ]
