# Generated by Django 3.0.6 on 2020-05-08 17:42

from django.db import migrations


def create_basic_users_group(apps, schema_editor):
    # very important to not import directly the model
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    basic_users_group, _ = Group.objects.get_or_create(name="basic_users")
    basic_users_group.permissions.add(
        *Permission.objects.filter(
            codename__in=[
                "view_newsitem",
                "add_newsitem",
                "change_newsitem",
                "delete_newsitem",
                "view_rating",
                "add_rating",
                "change_rating",
                "delete_rating",
            ]
        )
    )

    # *NOTE* on testing from the docs: https://docs.djangoproject.com/en/3.0/topics/testing/overview/
    #
    # these permissions can't be used during the tests as they will have not been commited to the test db
    #
    # Any initial data loaded in migrations will only be available in TestCase tests and not in TransactionTestCase tests,
    # and additionally only on backends where transactions are supported (the most important exception being MyISAM). This
    # is also true for tests which rely on TransactionTestCase such as LiveServerTestCase and StaticLiveServerTestCase.

    basic_users_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0018_auto_20200508_1729"),
    ]

    operations = [
        migrations.RunPython(create_basic_users_group),
    ]
