# Generated by Django 4.1.1 on 2022-09-19 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "A moderator accepted"),
                            ("rej_mod", "Rejected: A moderator rejected it"),
                            ("rej_fetch", "Rejected: Could not be fetched"),
                            ("rej_banned", "Rejected: Domain is blocklisted"),
                            ("rej_sentim", "Rejected: Sentiment analysis"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("target_url", models.URLField(unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("date", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "👍"), (-1, "👎"), (-100, "💩")], default=1
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="news.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "submission")},
            },
        ),
        migrations.CreateModel(
            name="Retrieval",
            fields=[
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="news.submission",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetched", "Fetched"),
                            ("rej_error", "Rejected: Could not fetch"),
                            ("rej_fetch", "Rejected: domain in blocklist"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "thumbnail_submitted",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "thumbnail_processed",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "thumbnail_from_page",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("fetched_page", models.TextField(blank=True, max_length=61440)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moderation",
            fields=[
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="news.submission",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Moderator accepted"),
                            ("rejected", "Moderator rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "target_url",
                    models.URLField(blank=True, default=None, null=True, unique=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="news.submission",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("passed", "Passed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True, default=None, null=True)),
                ("sentiment", models.TextField(blank=True, default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
