# Generated by Django 3.0.6 on 2020-06-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.CharField(choices=[('new', 'Processing'), ('accepted', 'Ready for review'), ('rej_fetch', 'Rejected: Could not fetch'), ('rej_list', 'Rejected: Blacklisted domain')], default='new', editable=False, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fetched_page', models.TextField(blank=True, default=None, editable=False, max_length=61440, null=True)),
                ('fetched_date', models.DateTimeField(default=None, editable=False, null=True)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(blank=True, default=None, editable=False, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'Processing'), ('ready', 'Ready for review'), ('accepted', 'Accepted'), ('rej_spam', "Rejected: It's spam"), ('rej_dupe', 'Rejected: Duplicate'), ('rej_votes', 'Rejected: Users downvoted'), ('rejected', 'Rejected: Other')], default='new', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bot_title', models.CharField(blank=True, default=None, editable=False, max_length=120, null=True)),
                ('bot_description', models.CharField(blank=True, default=None, editable=False, max_length=250, null=True)),
                ('bot_summary', models.TextField(blank=True, default=None, editable=False, null=True)),
                ('bot_sentiment', models.TextField(blank=True, default=None, editable=False, null=True)),
                ('bot_thumbnail', models.CharField(blank=True, default=None, editable=False, max_length=250, null=True)),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_submissions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(blank=True, default=None, editable=False, max_length=250, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('moderated_submission', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.ModeratedSubmission')),
                ('submitter', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '👍'), (-1, '👎'), (-100, '💩')], default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('moderated_submission', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='news.ModeratedSubmission')),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'moderated_submission')},
            },
        ),
    ]
