# Generated by Django 3.0.6 on 2020-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200620_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedsubmission',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='moderatedsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Processing'), ('ready', 'Ready for review'), ('accepted', 'Published'), ('rej_spam', "Rejected: It's spam"), ('rej_dupe', 'Rejected: Duplicate'), ('rej_votes', 'Rejected: Users downvoted'), ('rejected', 'Rejected: Other')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='moderatedsubmission',
            name='target_url',
            field=models.URLField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='moderatedsubmission',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'Processing'), ('accepted', 'Moved to moderation'), ('rej_fetch', 'Rejected: Could not fetch'), ('rej_list', 'Rejected: Blacklisted domain'), ('rej_mod', 'Rejected: Moderator action')], default='new', editable=False, max_length=10),
        ),
    ]
