# Generated by Django 3.1.1 on 2020-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200621_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden (moderation action)')], default='visible', max_length=10),
        ),
    ]
