# Generated by Django 3.2.5 on 2021-08-10 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    replaces = [('news', '0009_auto_20210808_2153'), ('news', '0010_auto_20210809_1350'), ('news', '0011_fetched_status'), ('news', '0012_analysis_status'), ('news', '0013_submission_status'), ('news', '0014_fetched_thumbnail_image'), ('news', '0015_alter_fetched_thumbnail_image'), ('news', '0016_auto_20210809_2153'), ('news', '0017_alter_moderation_status'), ('news', '0018_rename_fetched_fetch'), ('news', '0019_alter_fetch_thumbnail_image'), ('news', '0020_auto_20210810_1039'), ('news', '0021_auto_20210810_1441'), ('news', '0022_alter_vote_submission')]

    dependencies = [
        ('news', '0008_auto_20210807_2212_squashed_0011_submission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.submission')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, default=None, null=True)),
                ('sentiment', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('passed', 'Passed')], default='pending', max_length=10)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.submission')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('fetched_page', models.TextField(blank=True, max_length=61440)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('rej_error', 'Rejected: Could not fetch'), ('rej_fetch', 'Rejected: domain in blocklist')], default='pending', max_length=10)),
                ('thumbnail_image', models.ImageField(null=True, upload_to=news.models.user_directory_path)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.submission')),
                ('target_url', models.URLField(blank=True, default=None, null=True, unique=True)),
                ('title', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Moderation passed'), ('rejected', 'Moderator rejected')], default='pending', max_length=10)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='moderatedsubmission',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='moderatedsubmission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='fetched_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='fetched_page',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='news.submission'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('owner', 'submission')},
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='moderated_submission',
        ),
        migrations.DeleteModel(
            name='ModeratedSubmission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'A moderator accepted'), ('rej_mod', 'Rejected: A moderator rejected it'), ('rej_fetch', 'Rejected: Could not be fetched'), ('rej_banned', 'Rejected: Domain is blocklisted'), ('rej_sentim', 'Rejected: Sentiment analysis')], default='pending', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='news.submission'),
            preserve_default=False,
        ),
    ]
