# Generated by Django 3.2.5 on 2021-08-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_fetch_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Moderator accepted'), ('rejected', 'Moderator rejected')], default='pending', max_length=10),
        ),
    ]
