# Generated by Django 3.2.5 on 2021-08-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch',
            name='generated_thumbnail',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
