http# NOTE:
#   This file can be used to send requests directly from
#   Visual Studio Code. All you need to do is install
#   teh "REST Client" addon (by Huachao Mao) and then open
#   this file.

#   It will add 'Send Request' buttons and a side window
#   to display results. You can edit, modify etc.

#   Documentation:
#   https://github.com/Huachao/vscode-restclient

###

@server=127.0.0.1:8000
@user=adminz
@passwd=XXXXXXXXXXXXXXXXX

###

# @name login
POST http://{{server}}/auth/login/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}

{
  "username": "{{user}}",
  "password": "{{passwd}}"
}

###

@authToken = {{login.response.body.token}}

###

GET http://{{server}}/newsItem/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}

###

POST http://{{server}}/newsItem/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}

{
  "target_url": "https://google.com",
  "title": "this is a title",
  "source": "examples.http",
  "submitter": "vscode"
}

###

# same but using token authentication
POST http://{{server}}/newsItem/
content-type: application/json
Authorization: Token {{authToken}}

{
  "target_url": "https://google.com/?q=test1",
  "title": "this is a title",
  "source": "examples.http",
  "submitter": "vscode"
}

###

GET http://{{server}}/newsItem/2/ratings/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}


###

POST http://{{server}}/newsItem/2/ratings/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}

{
  "rating": -2,
  "user": 1
}


###

PATCH http://{{server}}/newsItem/2/ratings/1/
content-type: application/json
Authorization: Basic {{user}} {{passwd}}

{
  "rating": -1
}


###
